name: function_tree
description: A simple library for parsing strings into callable function-trees.
version: 0.8.12
homepage: https://github.com/ram6ler/function-tree

environment:
  sdk: '>=2.12.0 <3.0.0'


